name: Release Please

on:
  push:
    branches:
      - release-next
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Release-Please
        run: |
          npx release-please github-release
          npx release-please release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
